### ISSUE TITLE
app crashes when launching

### ISSUE THREAD

**Issue by kas70** [Phantast/smartnavi#11]
I'm on CM 13 and using the latest f-droid version.
Version 2.0.4 (free) seems to work.
From logcat:
```
05-08 13:55:25.482  7372  7372 E AndroidRuntime: FATAL EXCEPTION: main
05-08 13:55:25.482  7372  7372 E AndroidRuntime: Process: com.ilm.sandwich, PID: 7372
05-08 13:55:25.482  7372  7372 E AndroidRuntime: Theme: themes:{default=overlay:system, iconPack:system, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}
05-08 13:55:25.482  7372  7372 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.ilm.sandwich/com.ilm.sandwich.OsmMap}: java.lang.IllegalArgumentException: provider doesn't exist: network
```

**Comment by Phantast** [comment]
I just released version 2.2.2f.
It should fix the bug. F-Droid should compile the update within one or two days. Please report if the error is fixed.

**Comment by Phantast** [comment]
Update is now ready on F-Droid.

**Comment by kas70** [comment]
The issue persists with version 2.2.2f.

**Comment by Phantast** [comment]
Maybe you can also try the playstore version that I just compiled. If it crashes, the built-in crash-reporting tool will give me a clue of what happens. Give it a try.
https://github.com/Phantast/smartnavi/blob/master/smartnaviapp/smartnaviapp-playstore-release.apk

**Comment by kas70** [comment]
The latest version from F-Droid (2.2.4f) works. Thanks!
