### ISSUE TITLE
Have error

### ISSUE THREAD

**Issue by clarkman2** [Phantast/smartnavi#16]
Hi,

I download your code and run at LG V20 android 7.
It doesn't locate the map.

I always have error "E/DynamiteModule: Failed to load DynamiteLoader: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.dynamite.DynamiteModule$DynamiteLoaderClassLoader" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.ilm.sandwich-1/base.apk"],nativeLibraryDirectories=[/data/app/com.ilm.sandwich-1/lib/arm64, /system/lib64, /vendor/lib64]]"

Do you know how to fix it?

**Comment by Phantast** [comment]
Do you have the Google Play Services Library installed next to your Android SDKs?

**Comment by clarkman2** [comment]
Hi, 
I found the problem. It is my fault. I should change API key for google map.
Thanks!

**Comment by Phantast** [comment]
Thanks for letting is know. 👍
