### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by pizzamaker** [Phantast/smartnavi#2]
Please add this app to F-Droid. A thread for it has been created: https://f-droid.org/forums/topic/smartnavi/

**Comment by Phantast** [comment]
Thanks pizzamaker! I would be delighted to add the app to F-Droid.
I responded in the forum you mentioned.

**Comment by Phantast** [comment]
F-Droid version is now readyon Github

**Comment by krt16s** [comment]
Could the remaining jar files be pulled from mavenCentral as well?

**Comment by Phantast** [comment]
Waiting for osmbonuspack to be added to mavencentral.
See here: https://github.com/MKergall/osmbonuspack/issues/108

**Comment by Phantast** [comment]
Now using jitpack as waiting for MavenCentral is hopeless.

**Comment by jamalm** [comment]
I'm sorry, who are you and what does that mean?

On Sunday, 13 December 2015, Christian <notifications@github.com> wrote:

> Now using jitpack as waiting for MavenCentral is hopeless.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Phantast/smartnavi/issues/2#issuecomment-164309098>.
>

-- 


This email originated from DIT. If you received this email in error, please 
delete it from your system. Please note that if you are not the named 
addressee, disclosing, copying, distributing or taking any action based on 
the contents of this email or attachments is prohibited. www.dit.ie

Is ó ITBÁC a tháinig an ríomhphost seo. Má fuair tú an ríomhphost seo trí 
earráid, scrios de do chóras é le do thoil. Tabhair ar aird, mura tú an 
seolaí ainmnithe, go bhfuil dianchosc ar aon nochtadh, aon chóipeáil, aon 
dáileadh nó ar aon ghníomh a dhéanfar bunaithe ar an ábhar atá sa 
ríomhphost nó sna hiatáin seo. www.dit.ie

Tá ITBÁC ag aistriú go Gráinseach Ghormáin – DIT is on the move to 
Grangegorman <http://www.dit.ie/grangegorman>

**Comment by Phantast** [comment]
@jamalm I guess you are recieving email notifications from a github issue for SmartNavi https://github.com/Phantast/smartnavi/issues/2

**Comment by jamalm** [comment]
Yes i am, i see that now, i'd forgotten i subscribed, sorry about that. I'm
a fan of the idea. Keep up the good work!

On Sunday, 13 December 2015, Christian <notifications@github.com> wrote:

> @jamalm <https://github.com/jamalm> I guess you are recieving email
> notifications from a github issue for SmartNavi #2
> <https://github.com/Phantast/smartnavi/issues/2>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Phantast/smartnavi/issues/2#issuecomment-164309353>.
>

-- 


This email originated from DIT. If you received this email in error, please 
delete it from your system. Please note that if you are not the named 
addressee, disclosing, copying, distributing or taking any action based on 
the contents of this email or attachments is prohibited. www.dit.ie

Is ó ITBÁC a tháinig an ríomhphost seo. Má fuair tú an ríomhphost seo trí 
earráid, scrios de do chóras é le do thoil. Tabhair ar aird, mura tú an 
seolaí ainmnithe, go bhfuil dianchosc ar aon nochtadh, aon chóipeáil, aon 
dáileadh nó ar aon ghníomh a dhéanfar bunaithe ar an ábhar atá sa 
ríomhphost nó sna hiatáin seo. www.dit.ie

Tá ITBÁC ag aistriú go Gráinseach Ghormáin – DIT is on the move to 
Grangegorman <http://www.dit.ie/grangegorman>

**Comment by krt16s** [comment]
Looks like some java files of the free flavor still require play-services, e.g. `:smartnavi:compileFreeReleaseJavaWithJavac/home/krt/src/fdroiddata/build/com.ilm.sandwich/smartnavi/src/main/java/com/ilm/sandwich/OsmMapActivity.java:56: error: package com.google.android.gms.appindexing does not exist`

**Comment by Phantast** [comment]
I fixed some dependencies that occured due to app indexing.
Thanks for your help @krt16s !

**Comment by krt16s** [comment]
Sorry for keeping you waiting.. got swamped in github mails. Should be building tomorrow, thanks for the fix.

**Comment by Phantast** [comment]
I can see it now in F-Droid. Thanks @krt16s
