### ISSUE TITLE
Unknown error installing F-Droid version

### ISSUE THREAD

**Issue by helfio** [Phantast/smartnavi#4]
I get this message and app doesn't install. Trying on Motorola MotoG 1st gen.

**Comment by helfio** [comment]
I meant F-Droid. Sorry the typo on the title.

**Comment by taranarmo** [comment]
Same problem on Motorola Defy+ running android 4.4.1. On nexus 7 with stock rom (android 6.x) installated fine.

**Comment by Phantast** [comment]
On all devices I tested, I could not detect any problem.
@helfio Which Android version is installed on your Moto G?

**Comment by aminb** [comment]
Getting the same error here on my Nexus 5, running CyanogenMod 13.0-20160112-NIGHTLY-hammerheadcaf (Android 6.0.1)

**Comment by taranarmo** [comment]
Cyanogenmod is on my Motorola defy+ too

**Comment by helfio** [comment]
CM13 20160112 nightly, android M

**Comment by sniperle** [comment]
Logcat: 
01-13 09:59:28.636 E/installd(262): Couldn't opendir /data/data/com.ilm.sandwich: No such file or directory
01-13 09:59:28.762 E/AppDetails(7786): Installer aborted with errorCode: 3

**Comment by Phantast** [comment]
Can you install the apk directly? You can download it here: https://f-droid.org/repo/com.ilm.sandwich_24.apk

**Comment by helfio** [comment]
I cannot install the apk, but in this case I don't get the message I reported but a screen with 'the apk wasn't installed' or so (I use the phone on Spanish) with a cross icon.

**Comment by tester007x** [comment]
Outbfrom logcat:
PackageManager: com.android.server.pm.PackageManagerException: Package com.ilm.sandwich requires unavailable shared library com.google.android.maps; failing!

**Comment by helfio** [comment]
I can confirm I have no gapps on my phone. This dependency should be removed before being available on F-Droid, though

**Comment by Phantast** [comment]
Indeed I fixed a Google dependency. Next F-Droid release should fix it.

**Comment by Phantast** [comment]
Version 2.0.4 is available on F-Droid now. Please report if issue can be closed.

**Comment by sniperle** [comment]
Works with CM13 without Gapps :-) Thanks

**Comment by Phantast** [comment]
Thanks @sniperle for the highspeed feedback! Looking forward to read about your experiences and suggestions.
