### ISSUE TITLE
not understanding how to use offline maps, 'follow our tutorial' always pops up

### ISSUE THREAD

**Issue by kn00tcn** [Phantast/smartnavi#8]
i followed the instructions, generated the files... but where am i supposed to place them? is the root of internal storage not the right location? (the one that a computer sees via MTP) or is the MOBAC export not the right format? ( i started googling the path & saw this https://github.com/osmdroid/osmdroid/issues/21 )

CM13 no gapps

the other thing is the online map was empty, but i just noticed location & storage were disabled in app permissions (part of android, but dont exist in CM privacy guard), so i have an online map now but still no offline one

now how am i supposed to clear a set destination?

**Comment by Phantast** [comment]
If you follow the tutorial that you can open from inside the pop-up, everything is clearly stated. Or see here http://smartnavi-app.com/offline
There you can also see which format of tiles has to be used and where to place them. 
The .jpg problem should already be solved in Smartnavi. 
Please enable permissions for Smartnavi to read storage, otherwise it can not read your tiles. 
Android 6 Permission Handling is currently in implementation.

**Comment by Phantast** [comment]
Regarding: How to clear a set destination?
Currently you can set a new destination, which removes the old destination and route. 
There is no way to just clear it. Can easy be implemented. Any idea how you would like to reach it? As a context menu when tipping the final destination marker?

**Comment by kn00tcn** [comment]
it's always safest to put things in menus (even if they are duplicates of longpress on map) since the user always goes to the menu when they dont know what to do

i did follow the tutorial, i generated the map files, placed them into internal storage in the folder structure specified... it is not clear if the app is even trying to load them or not, a warning message would be nice (such as 'warning: unable to load map data from /storage/osmdroid/maps/1234'), or can i see what point it's failing with android's internal logging?

reason i ask about the exact location is there are multiple locations on multiple devices, sd card/internal/system/etc

here's a potential idea, have the app generate the folder structure, this would confirm that storage is accessible & also guide the user into placing the files into it

**Comment by Phantast** [comment]
- The problem with multiple Tutorials showing up is fixed in version 2.2.0.
- A route which has been drawn can now be removed by pressing the back button on your device
